### ISSUE TITLE
Tennis.csv update

### ISSUE THREAD

**Issue by LePetitNewbie** [dylanwebbc/TennisPredictionModel#1]
Hi Dylan,
          I am trying to understand how your model works. I have no experience with coding. I managed to run the codes but I was wondering how will the Tennis.csv update? I added the atp_matches_2021.csv to the tennis_atp-master folder. I ran the "tennisstatsgenerator.py" in pycharm but when I check on the "Tennis.csv" file, it still shows Roland Garros 2020 as the last tournament in that particular file. Do I need to do it manually? 

The tennispredictionmodel.py also works fine.

I hope you can help. Great work anyways. Take care

Cheers
Ol

**Comment by dylanwebbc** [comment]
Hi there!

Great question. If you run the line **updateFiles(2021, "Australian Open")**, the tennis.csv file will be updated with the new tournament information. Just make sure not to run it multiple times! :)

-Dylan

**Comment by LePetitNewbie** [comment]
Hi Dylan,
       Thanks for getting back to me. I ran the line and it worked perfectly. Appreciate your time and your work.

All the bests.
Ol

**Comment by LePetitNewbie** [comment]
Hi Dylan, 
Hope you are well mate. Quick question for you, The Rome and Madrid Masters were played in the last couple of weeks. Do I do the same for the update when it comes to those tournament (updateFiles(2021, "Rome Masters")? or do I run updateFiles(2021, "anything", fullUpdate = True) every week? ...I am asking this because I noticed that whenever I am updating files 'anything', its been showing "creating.stats.csv with the same total (6578) for the past 3 weeks. 

For what its worth, I have been trying your model on a few tournaments and it has been really good with a few unreal picks ! 

I also have a golf question. I hope you do not mind. 

Cheers
Ol

**Comment by dylanwebbc** [comment]
Hey there,

Good question--I wrote this model for predicting the grand slams, so I'm glad to hear it's working well with other tournaments!  The line updateFiles(2021, "Rome Masters") should do the trick. That way you don't have to wait for it to recompile all the statistics each time :)

-Dylan

**Comment by LePetitNewbie** [comment]
Hi Dylan
      Yeah it has work nicely on a few tournaments.  Thanks again for responding to both the tennis and golf question. 

Take care
Ol
